services:
  postgres:
    image: postgres:16
    container_name: quarkus-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: quarkus-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"

  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/userdb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: quarkus-crud
      KEYCLOAK_CLIENT_ID: quarkus-crud-client
      KEYCLOAK_CLIENT_SECRET: change-me
      CORS_ORIGINS: http://localhost:5173
      AUTH_REFRESH_COOKIE_SECURE: "false"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak

volumes:
  postgres_data:
